### ISSUE TITLE
Kue for queing crawler jobs

### ISSUE THREAD

**Issue by digitarald** [mozilla/prowac#13]
Seems to be the best in class and even gives us a UI to show state of the queue https://github.com/Automattic/kue

Whatcha think? @TimAbraldes @zalun

**Comment by TimAbraldes** [comment]
I like it! I'm working up a patch that uses kue.

One concern is that it locks us in to redis; if we realize later on that our memory concerns were justified, we'll be kind of stuck and we'll have to rip this out.

**Comment by digitarald** [comment]
Redis for job management is great, as it is perfect for queues. If we realize later that we should store _crawler results_ in some other solution, we should just change the DB that specific purpose.

**Comment by TimAbraldes** [comment]
Closed via #15
