### ISSUE TITLE
Separate dataStore/backend-redis and kue databases

### ISSUE THREAD

**Issue by TimAbraldes** [mozilla/prowac#36]
Running the crawler generates a 'dump.rdb' file from redis. Removing that file gets rid of url jobs and also the entire data store.

It would be ideal if we had two separate config options:
1. Specifies redis options for the dataStore backend
2. Specifies redis options for the kue backend

**Comment by zalun** [comment]
I'm running the crawler locally and I don't see this file...
Should I see this file?
@digitarald can you confirm you see this file?

**Comment by digitarald** [comment]
The saving of snapshots should only happen locally, not on heroku. Not sure if 2 instances of redis make sense for us other than separate snapshots. Sounds like the use case we are looking for is emptying the queue, right?

**Comment by zalun** [comment]
I don't see it at all - I mean I've got no file. I think it depends on redis configuration.
