### ISSUE TITLE
zlib errors are not caught in node-fetch

### ISSUE THREAD

**Issue by digitarald** [mozilla/prowac#50]
The whole process fails when zlib bails, which is unexpected in itself as kue should recover.

```
[1458355807536] start - japanpost.jp
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)
```

https://stackoverflow.com/questions/35439074/how-do-i-catch-zlib-errors-in-node-js suggests to catch errors from the decompressed stream which needs to be done in https://github.com/bitinn/node-fetch/blob/258c036ca75fb35bb0080612f61db6a3945a23ae/index.js#L159

**Comment by zalun** [comment]
can't reproduce it with japanpost.jp ...
`npm run start:crawler -- --urls japanpost.jp`
do we have a site which will fail?
