### ISSUE TITLE
Consider open crawl data

### ISSUE THREAD

**Issue by digitarald** [mozilla/prowac#58]
Skimmed over both to assess what kind of data they could provide:

https://commoncrawl.org/
- Focused on text, doesn't crawl as much JS and CSS

http://httparchive.org/
- Mozilla is sponsor
- Crawls images, CSS and JS

We need to do some more research, but httparchive might be good alternative to Prowac crawling sites.

**Comment by digitarald** [comment]
@zalun can you take a look as well?

**Comment by zalun** [comment]
httparchive
- pages scheme - http://pastebin.com/6Kx9i3Q4
- 25 pages - http://pastebin.com/w1UTJrLW
- requests scheme - http://pastebin.com/Ws7Lufkh
- 25 requests - http://pastebin.com/d9XTZk9P

sample queries:
https://www.igvita.com/2013/06/20/http-archive-bigquery-web-performance-answers/

**Comment by digitarald** [comment]
httparchive

> … The HTTP Archive provides this record. It is a permanent repository of web performance information such as size of pages, failed requests, and technologies utilized.

It is just request/response details and WebPagetest results on purpose.

Looks like they are both not a good fit, not even giving us an edge in priming the database.

**Comment by miketaylr** [comment]
There's also http://webdevdata.org/, but it's just HTTP requests and HTML responses for home pages.

**Comment by digitarald** [comment]
On top of that debdevdata.org just has about 8000 entries.

**Comment by marcoscaceres** [comment]
> On top of that debdevdata.org just has about 8000 entries.

That's ~80,000. Law of diminishing returns kicks in pretty quick after that. Admittedly, our (webdevdata's) dataset is grossly out of date now - but a new run could be performed. I produced the following report on [iOS "PWAs"](https://github.com/w3c-webmob/installable-webapps/blob/gh-pages/ios_standalone/README.md) previously from that old dataset.
